# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# trigger:
# - master

jobs:
- job: Ubuntu
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - script: printenv

  - script: |
      sudo apt-get update
      sudo apt-get install g++ cmake libfftw3-dev libfftw3-single3 libmpich-dev
    displayName: 'Install dependencies'

  - script: cmake --version

  - script: g++ --version

  - script: cat /proc/cpuinfo | awk '/^processor/{print $3}' | wc -l

  - script: |
      mkdir -p build
      cd build
      CXX=g++ cmake ..
      make -j4
    displayName: 'Build'

  - script: |
      mpirun -n 2 ./build/main
    displayName: 'Run main'


- job: macOS
  pool:
    vmImage: 'macOS-10.14'

  steps:
  - script: |
      /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    displayName: 'Install Homebrew'

  - script: |
      brew install --with-toolchain llvm
      brew install cmake
      brew install fftw
      brew install open-mpi
    displayName: 'Install dependencies'

  - script: /usr/local/opt/llvm/bin/clang++ --version

  - script: cmake --version
