# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

container: ubuntu:18.04

steps:
- script: printenv

- script: |
    sudo apt-get update
    sudo apt-get install g++ cmake libfftw3-dev libfftw3-single3 libmpich-dev
  displayName: 'Install dependencies'

- script: |
    mkdir -p build
    cd build
    CXX=g++ cmake ..
    make -j4
  displayName: 'Build'

- script: |
    mpirun -n 2 ./build/main
  displayName: 'Run main'

